### ISSUE TITLE
Unknown type name 'NSString' for objc code

### ISSUE THREAD

**Issue by kostiakoval** [paulsamuels/SBConstants#15]
.../Source/Storyboard/StoryboardIdentifiers.m:3:9: In file included from 
 `error: unknown type name 'NSString' extern NSString * const SomeCell;`

There is no Foundation import for generated objc file. If I add id manual it works

**File Content**
```
// Auto generated file - any changes will be lost


#pragma mark - tableViewCell.reuseIdentifier
extern NSString * const SomeCell;
```

**Comment by orta** [comment]
This was fixed earlier - https://github.com/paulsamuels/SBConstants/commit/b77cb7137d40c7a75841981484ea45d8c37e23ca

I've pushed v1.1.1 just now which should bring it to everyone.

**Comment by kostiakoval** [comment]
Thanks @orta, you are the best! ))

**Comment by geekazoid-at** [comment]
Hi @orta, I made sure I have 1.1.1 on my machine but I am still having the problem with the missing import. The only way I can get it to work is with a pch file in XCode.

**Comment by orta** [comment]
I've deployed 1.1.2  with the changes since jan, see if that fixes it for you.

**Comment by geekazoid-at** [comment]
Now it works flawlessly. Thanks @orta... great!!!
